apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: redis-test
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  clusterIP: "None"